# Global Configuration
encoding: UTF-8
timezone: Etc/UTC
theme: null

# Build Command Options
strict_front_matter: true

# Liquid Options
error_mode: strict
strict_variables: true
strict_filters: true

# Front Matter defaults
defaults:
    -
        scope:
            path: ""
        values:
            layout: "page"
            copyright: "bachsau"
            canonical: null
